elasticsearch:
  enabled: true
  image: docker.elastic.co/elasticsearch/elasticsearch
  imageTag: 7.17.3
  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
  replicas: 1
  minimumMasterNodes: 1
  antiAffinity: "soft"
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  esJavaOpts: "-Xmx512m -Xms512m"
  resources:
    requests:
      cpu: "100m"
      memory: "1024M"
    limits:
      cpu: "1000m"
      memory: "1024M"
neo4j:
  enabled: true
  image:
    repository: neo4j
    tag: 5.11.0
    # tag: 5.11.0-community
  nameOverride: neo4j
  neo4j:
    name: neo4j
    edition: "community"
    acceptLicenseAgreement: "yes"
    defaultDatabase: "graph.db"
    passwordFromSecret: neo4j-secrets
  # Set security context for pod
  securityContext:
    runAsNonRoot: true
    runAsUser: 7474
    runAsGroup: 7474
    fsGroup: 7474
    fsGroupChangePolicy: "Always"
  # Disallow privilegeEscalation on container level
  containerSecurityContext:
    allowPrivilegeEscalation: false
  volumes:
    data:
      mode: "defaultStorageClass"
      defaultStorageClass:
        requests:
          storage: 1Gi
  env:
    NEO4J_PLUGINS: '["apoc"]'
mysql:
  enabled: true
  image:
    repository: bitnami/mysql
    tag: 8.0.32-debian-11-r26
  auth:
    existingSecret: mysql-secrets
  primary:
    extraFlags: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
    persistence:
      size: 1Gi
kafka:
  enabled: true
  version: 30.0.4
  app_version: 3.8.0
  image:
    repository: "bitnami/kafka"
    tag: "3.8.0-debian-12-r3"
  listeners:
    client:
      protocol: 'PLAINTEXT'
    interbroker:
      protocol: 'PLAINTEXT'
  controller:
    replicaCount: 0
  broker:
    replicaCount: 1
    minId: 0
    extraConfig: |
      message.max.bytes=5242880
      default.replication.factor=1
      offsets.topic.replication.factor=1
      transaction.state.log.replication.factor=1
  kraft:
    enabled: false
  zookeeper:
    enabled: true
    image:
      repository: bitnami/zookeeper
      tag: 3.9.1-debian-12-r13
