---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "anbae-pv-claim"
  labels:
    app: "anbae"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: anbae
  labels:
    app: anbae
spec:
  volumes:
    - name: anbae-pv-storage
      persistentVolumeClaim:
        claimName: anbae-pv-claim
  containers:
    - name: interactive
      image: registry.gitlab.sdu.dk/jah/bigdatarepo/interactive:latest
      imagePullPolicy: Always
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
        - mountPath: "/root/code"
          name: anbae-pv-storage