---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interactive-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interactive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interactive
  template:
    metadata:
      labels:
        app: interactive
    spec:
      containers:
        - name: interactive
          image: registry.gitlab.sdu.dk/jah/bigdatarepo/interactive:latest
          imagePullPolicy: Always
          command: ["/bin/sleep", "3650d"]
          volumeMounts:
            - name: interactive-storage
              mountPath: /root/code
          # env:
          #   - name: KAFKA_SASL_USERNAME
          #     value: "user1"
          #   - name: KAFKA_SASL_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: kafka-user-passwords
          #         key: client-passwords
      volumes:
        - name: interactive-storage
          persistentVolumeClaim:
            claimName: interactive-pvc