---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "datanode-claim"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-datanode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hdfs-datanode
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      volumes:
        - name: datanode-storage
          persistentVolumeClaim:
            claimName: datanode-claim
      containers:
        - name: hdfs-datanode-1
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          volumeMounts:
            - name: datanode-storage
              mountPath: "/hadoop/dfs/data"
              
          env:
            - name: SERVICE_PRECONDITION
              value: "namenode:9870"

            - name: CORE_CONF_hadoop_http_staticuser_user
              value: "root"
            - name: CORE_CONF_hadoop_proxyuser_hue_hosts
              value: "*"
            - name: CORE_CONF_hadoop_proxyuser_hue_groups
              value: "*" 
            - name: CORE_CONF_io_compression_codecs
              value: "org.apache.hadoop.io.compress.SnappyCodec"

            - name: HDFS_CONF_dfs_webhdfs_enabled
              value: "true"
            - name: HDFS_CONF_dfs_permissions_enabled
              value: "false"
            - name: HDFS_CONF_dfs_permissions
              value: "false"
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
          ports:
            - containerPort: 9864