apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  ports:
    - name: web
      protocol: TCP
      port: 9870
      targetPort: 9870
    - name: rpc
      protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: datanode1
spec:
  selector:
    app: datanode1
  ports:
    - name: datanode1
      protocol: TCP
      port: 9864
      targetPort: 9864

---
apiVersion: v1
kind: Service
metadata:
  name: datanode2
spec:
  selector:
    app: datanode2
  ports:
    - name: datanode2
      protocol: TCP
      port: 9865
      targetPort: 9864

---
apiVersion: v1
kind: Service
metadata:
  name: datanode3
spec:
  selector:
    app: datanode3
  ports:
    - name: datanode3
      protocol: TCP
      port: 9866
      targetPort: 9864
