apiVersion: v1
kind: ConfigMap
metadata:
  name: sqoop-config
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <configuration>
        <property>
            <name>fs.defaultFS</name>
            <value>hdfs://namenode.svane.svc.cluster.local:9000</value>
        </property>
    </configuration>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqoop
  template:
    metadata:
      labels:
        app: sqoop
    spec:
      containers:
        - name: sqoop
          image: dvoros/sqoop:latest
          envFrom:
            - configMapRef:
                name: sqoop-config
          volumeMounts:
            - name: sqoop-config-volume
              mountPath: /etc/hadoop/conf
          command: ["/bin/bash", "-c", "--"]
          args:
            - >
              curl -L -o /tmp/postgresql-42.2.24.jar https://jdbc.postgresql.org/download/postgresql-42.2.24.jar &&
              while true; do sleep 30; done;
          env:
            - name: HADOOP_CLASSPATH
              value: "/tmp/postgresql-42.2.24.jar"
      volumes:
        - name: sqoop-config-volume
          configMap:
            name: sqoop-config
---
apiVersion: v1
kind: Service
metadata:
  name: sqoop
spec:
  selector:
    app: sqoop
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
