apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-config
  labels:
    app: hive-metastore
data:
  metastore-site.xml: |-
    <configuration>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>jdbc:postgresql://postgresql:5432/hive</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>org.postgresql.Driver</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>hive</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>hive</value>
        </property>
        <property>
            <name>hive.metastore.uris</name>
            <value>thrift://hive-metastore:9083</value>
        </property>
        <property>
            <name>datanucleus.autoCreateSchema</name>
            <value>false</value>
        </property>
        <property>
            <name>hive.metastore.schema.verification</name>
            <value>true</value>
        </property>
    </configuration>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-entrypoint
  labels:
    app: hive-metastore
data:
  entrypoint.sh: |-
    #!/bin/bash
    export HADOOP_VERSION=3.3.1
    export METASTORE_VERSION=3.1.2
    export AWS_SDK_VERSION=1.11.901
    export LOG4J_VERSION=2.8.2
    export JAVA_HOME=/usr/local/openjdk-8
    export HADOOP_HOME=/opt/hadoop-${HADOOP_VERSION}
    export HIVE_HOME=/opt/apache-hive-metastore-${METASTORE_VERSION}-bin
    export HADOOP_CLASSPATH=${HADOOP_HOME}/share/hadoop/tools/lib/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar:${HADOOP_HOME}/share/hadoop/tools/lib/hadoop-aws-${HADOOP_VERSION}.jar:${HIVE_HOME}/lib/log4j-core-${LOG4J_VERSION}.jar:${HIVE_HOME}/lib/log4j-api-${LOG4J_VERSION}.jar:${HIVE_HOME}/lib/log4j-1.2-api-${LOG4J_VERSION}.jar:${HIVE_HOME}/lib/log4j-slf4j-impl-${LOG4J_VERSION}.jar

    ${HIVE_HOME}/bin/schematool -initSchema -dbType postgres -userName hive -passWord hive
    ${HIVE_HOME}/bin/start-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
        - name: init-wait-db
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              until nc -z -v -w90 postgresql 5432; do
                echo "Waiting for Hive Metastore DB to be ready..."
                sleep 5
              done
      containers:
        - name: metastore
          image: rtdl/hive-metastore:3.1.2
          command: ["bash", "/opt/entrypoint/entrypoint.sh"]
          ports:
            - containerPort: 9083
              name: thrift
          volumeMounts:
            - name: hive-config
              mountPath: /opt/apache-hive-metastore-3.1.2-bin/conf
            - name: entrypoint
              mountPath: /opt/entrypoint
      volumes:
        - name: hive-config
          configMap:
            name: hive-metastore-config
        - name: entrypoint
          configMap:
            name: hive-metastore-entrypoint
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP
  selector:
    app: hive-metastore
