version: 9.2.9
app_version: 3.5.2
master:
  configMap: spark-config
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
worker:
  configMap: spark-config
  replicaCount: 2
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi