name: Build and push - service/kafka-connect

on:
  push:
    tags: 
      - "v*"
  pull_request:
    branches:
      - main
      - "releases/**"
    paths: 
      - "services/kafka-connect/**"
      - ".github/workflows/**kafka-connect.yml"

env:
  USERNAME: jah
  REGISTRY: registry.gitlab.sdu.dk
  IMAGE_NAME: bigdatarepo/kafka-connect
  CP_VERSION: "7.4.10"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:services/kafka-connect/"
          platforms: linux/amd64,linux/arm64
          build-args: "CP_VERSION=${{ env.CP_VERSION }}"
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.CP_VERSION }}
            ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
