name: Build and push - service/interactive

on:
  push:
    tags: ["v*"]
  pull_request:
    branches:
      - main
      - 'releases/**'
    paths: 
      - "services/interactive/**"
      - ".github/workflows/**interactive.yml"

env:
  USERNAME: jah
  REGISTRY: registry.gitlab.sdu.dk
  IMAGE_NAME: bigdatarepo/interactive
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:services/interactive/"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
          